Gruppe52/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('', include('matega.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matega/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('', views.index, name='index'),
    path('ingredient_search/', views.ingredient_search, name='ingredient_search'),
    path('signup/', views.signup, name="signup"),
    path('recipe/<recipe_id>', views.recipe, name='recipe'),
    path('my_recipes/<user_id>', views.my_recipes, name='my_recipes'),
    path('chef_site/<chef_id>', views.chef_site, name='chef_site'),
    path('my_site/<user_id>', views.chef_site_2, name='my_site'),
    path('add_recipe', views.add_recipe, name='add_recipe'),
    path('chef_edit', views.chef_edit, name='chef_edit'),
    path('authorize_chef/', views.authorize_chef, name='authorize_chef'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/add_recipe_to_user/$', views.add_recipe_to_user, name='add_recipe_to_user'),
    url(r'^ajax/remove_recipe_from_user/$', views.remove_recipe_from_user, name='remove_recipe_from_user'),
    url(r'^ajax/is_fav_recipe/$', views.is_fav_recipe, name='is_fav_recipe'),
    url(r'^ajax/add_rating/$', views.add_rating, name='add_rating'),
    url(r'^ajax/sort_by_ingredients/$', views.sort_by_ingredients, name='sort_by_ingredients'),
]

matega/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
import datetime
import os
from .choices import *


def get_image_path(instance, filename):
    return os.path.join('images', str(instance.id), filename)


class User(AbstractUser):
    is_chef = models.BooleanField(default=False)
    asked_for_perm = models.BooleanField(default=False)
    saved_recipes = models.ManyToManyField('Recipe', blank=True)

    def add_recipe_to_fav(self, recipe_id):
        for recipe_ in Recipe.objects.all():
            if recipe_.id == recipe_id:
                self.saved_recipes.add(recipe_id)
                print(self.saved_recipes.values_list())

    def remove_recipe_from_fav(self, recipe_id):
        for recipe_ in self.saved_recipes.values_list():
            if recipe_[0] == recipe_id:
                self.saved_recipes.remove(recipe_)
                print(self.saved_recipes.values_list())


class Chef(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_chef")
    workplace = models.CharField(max_length=100)
    image = models.ImageField(upload_to=get_image_path, blank=True, default="default_m.png")
    info = models.TextField()
    merit = models.CharField(max_length=75, default="")
    education = models.CharField(max_length=75, default="")

    def __str__(self):
        return self.user.first_name+' '+self.user.last_name


class Ingredient(models.Model):
    ingredient = models.CharField(max_length=30)
    ingredient_type = models.CharField(max_length=30, choices=ingredient_choices)

    def __str__(self):
        return self.ingredient


class ValueIngredient(models.Model):
    value = models.CharField(max_length=30)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.value) + " " + self.ingredient.__str__()


class Recipe(models.Model):
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30)
    ingredients = models.ManyToManyField(Ingredient)
    values = models.ManyToManyField(ValueIngredient)
    pub_date = models.DateTimeField('date published', null=True)
    recipe_text = models.TextField(null=True)
    num_stars = models.IntegerField(null=True)
    image = models.ImageField(upload_to=get_image_path, blank=True, default="default_m.png")

    def __str__(self):
        return self.name

    def add_value_to_values(self, value):
        self.values.add(value)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_rating")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="recipe_rating")
    rating = models.IntegerField(null=True)

matega/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Recipe, Ingredient, Chef, ValueIngredient
from .choices import *


# Registrering av kokk
class ChefUserForm(UserCreationForm):
    workplace = forms.CharField(max_length=254)
    info = forms.CharField(widget=forms.Textarea(attrs={'width': "100%", 'cols': "80", 'rows': "3", }))
    image = forms.ImageField(required=False)
    education = forms.CharField(max_length=75)
    merit = forms.CharField(max_length=75)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username')


# Endring av kokkeinformasjon
class ChefEditForm(forms.ModelForm):
    workplace = forms.CharField(max_length=254, required=True)
    info = forms.CharField(required=True, max_length=1500, widget=forms.Textarea(
        attrs={'width': "100%", 'cols': "80", 'rows': "3", }))
    image = forms.ImageField(required=True)
    education = forms.CharField(max_length=75, required=True)
    merit = forms.CharField(max_length=75, required=True)

    class Meta:
        model = Chef
        fields = ['workplace', 'info', 'image', 'education', 'merit']


# Bruker registrering
class UserForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User


# Registrering av ingredienser
class AddIngredientForm(forms.ModelForm):
    ingredient = forms.CharField(required=True, label='Ingrediens', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Ingrediens: Eks. melk, hvete, entrecote'
        }
    ))
    ingredient_type = forms.ChoiceField(required=True, label='Velg kategori',
                                        initial='Velg kategori', choices=ingredient_choices)

    class Meta:
        model = Ingredient
        fields = ['ingredient', 'ingredient_type']


# Registrering av oppskrifter
class RecipeModelForm(forms.ModelForm):
    name = forms.CharField(label='Oppskriftsnavn', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Skriv inn oppskriftsnavn'
        }
    ))
    pub_date = forms.DateTimeField(
        required=False,
        label='Publiseringsdato',
        widget=forms.DateInput(
            format='%m/%d/%Y %H:%M',
            attrs={
                'class': 'form-control',
                'readonly': 'True'
            }
        ))
    recipe_text = forms.CharField(required=False, widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Skriv inn fremgangsmåte & info'
        }
    ))
    num_stars = forms.IntegerField(required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'readonly': 'True',
            'placeholder': 'Du kan ikke sette stjernekast på egen oppskrift'
        }
    ))

    class Meta:
        model = Recipe
        fields = ['name', 'ingredients', 'pub_date', 'recipe_text', 'num_stars', 'image']


# Registrering av ingredienser med en spesifikk verdi
class AddValueIngredient(forms.ModelForm):
    value = forms.CharField(label='Ingrediensverdi', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Skriv inn mengde'
        }
    ))

    class Meta:
        model = ValueIngredient
        fields = ['value']

templates/add_recipe.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
    Add recipe
{% endblock %}

{% block css %}
{% endblock %}
    .form_ingredients {
        height: 600px;
    }
{% block content %}
    <div class="container">
        <div class="row">
            <!--Form for å legge til oppskrifter-->
            <form method="post" enctype="multipart/form-data" class="col-lg-9">
                {% csrf_token %}
                {% with WIDGET_ERROR_CLASS="is-invalid" %}
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group">
                                {% render_field form.chef %}
                                <h4>Lag oppskrift</h4>
                                {% render_field form.name class="form-control mb-2"%}
                                <small class="text-danger">{{ form.name.errors }}</small>
                                {% render_field form.recipe_text class="form-control mb-2" %}
                                <small class="text-danger">{{ form.recipe_text.errors }}</small>

                                {% render_field form.pub_date class="form-control mb-2"%}
                                <small class="text-danger">{{ form.pub_date.errors }}</small>

                                <h4>Legg til bilde</h4>

                                {% render_field form.image %}
                                <small class="text-danger">{{ form.image.errors }}</small>

                                <button type="submit" class="btn btn-success float-right" name="recipe_form">Lag oppskrift!</button>
                            </div>
                        </div>
                        <div class="col-lg-4">
                                <h4>Velg ingredienser:</h4>
                                {% render_field form.ingredients class="form-control form_ingredients" size="15"%}
                        </div>
                    </div>
                {% endwith %}
            </form>
            <!--Form for å legge til ingredienser-->
            <form method="post" id="add_ingredient_form" class="col-lg-3">
                {% csrf_token %}
                    {{ ingredient_form.errors }}
                    <h4>Legg til ingrediens</h4>
                    {% render_field ingredient_form.ingredient class="form-control mb-2" %}
                    {% render_field ingredient_form.ingredient_type class="form-control mb-2" %}
                    <br>
                    <button type="submit" class="btn btn-success float-right" name="ingredient_form">Legg til</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
    //Mousedown event for å kunne velge flere ingredienser uten ctrl
    $('#id_ingredients option').mousedown(function(e) {
        e.preventDefault();
        $(this).prop('selected', !$(this).prop('selected'));
        return false;
    });
    //lagrer informasjon om oppskrift i session storage før siden lastes ut
    window.onbeforeunload = function() {
        sessionStorage.setItem("name", $('#id_name').val());
        sessionStorage.setItem("recipe_text", $('#id_recipe_text').val());

        let arr = $("#id_ingredients").val();
        sessionStorage.setItem("chosen_ingredients", JSON.stringify(arr));
    };

    //henter informasjon om oppskrift fra session storage når siden lastes inn
    window.onload = function() {
        let name = sessionStorage.getItem("name");
        let recipe_text = sessionStorage.getItem("recipe_text");
        $("#id_name").val(name);
        $("#id_recipe_text").val(recipe_text);

        let chosen_ingredients = JSON.parse(sessionStorage.getItem("chosen_ingredients"));
        let arr = [];
        chosen_ingredients.forEach( function (i) {
           arr.push(parseInt(i));
        });
        $("select").val(arr);
    };
    </script>
{% endblock %}

templates/add_values.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
    Add values
{% endblock %}

{% block css %}
{% endblock %}
    .forms {
        height: 600px;
    }
{% block content %}
    <div class="container justify-content-center col-lg-8">
        <div class="row">
            <h4>Legg til mengde for hver ingrediens</h4>
                 <table class="table table-bordered">
                    <thead>
                        <th>Mengde</th>
                        <th>Ingrediens</th>
                    </thead>
                    <tbody>
                        {% for form in forms %}
                            <tr>
                                <td>
                                    <form id="form_{{ forloop.counter }}" name="form_{{ forloop.counter }}"
                                          method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% with WIDGET_ERROR_CLASS="is-invalid" %}
                                        <input type="text" name="recipe" style="display: none"
                                               placeholder="Recipe" id="r_{{ forloop.counter }}" required="">
                                        <input type="text" name="ingredient" style="display: none"
                                               placeholder="Ingrediens" id="{{ forloop.counter }}" required="">
                                        {% render_field form.value class="form-control mb-2"%}
                                    {% endwith %}
                                    </form>
                                </td>
                                <td id="td_{{ forloop.counter }}">

                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row">
                <input type="button" value="Fullfør!" onclick="submitForms()" class="btn btn-success" />
            </div>
            <!-- Lager <td>-ene som legges til i tabellen over etter page-load -->
            <div class="col-lg-4" style="display: none">
                <table class="table table-border">
                    <tbody>
                        <th scope="col">Ingrediens</th>
                        {% for ing in ingredients %}
                            <tr id="tr_{{ forloop.counter }}">
                                <td id="td2_{{ forloop.counter }}">
                                    {{ ing.ingredient }}
                                </td>
                                <td id="ing_id_{{ forloop.counter }}">{{ ing.id }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>
{% endblock %}
{% block script %}
    <script>

    //sjekker om ingrediensform er valid
    function isValidForm()
    {
        var len = "{{ length }}";
        console.log(len);
        for (let i=1; i<=len; i++) {
            var inp = document.forms["form_" + i]["value"].value;
            if (inp == null || inp == "") {
                alert("Vennligst fyll ut alle feltene");
                return false;
            }
        }
        return true;
    }

    //Sender inn alle valueingredient forms
    function submitForms(){
        if (isValidForm()) {
            $('form').each(function () {
                var that = $(this);
                $.post(that.attr('action'), that.serialize());
            });
            var delayInMilliseconds = 500;

            setTimeout(function() {
                location.href = "recipe/{{ recipe.id }}";
            }, delayInMilliseconds);
        }
    }
    
    $( document ).ready(function () {
        // Legger til input-feltene i rett rad i tabellen på siden
        var len = "{{ length }}";
        console.log(len);
        for (let i=1; i<=len; i++){
            var td = document.getElementById("td_"+i);
            var td2 = document.getElementById("td2_"+i);
            var ing_id = document.getElementById("ing_id_"+i);
            var ren = document.getElementById(i);
            var rec = document.getElementById("r_"+i);
            rec.value = {{ recipe.id }};
            console.log(ing_id.innerText);
            ren.value = ing_id.innerText;
            console.log(ren);
            // var valueForm = document.forms['form_'+i];
            // valueForm.elements["ingredient"].value(td2.innerText);
            console.log(td);
            console.log(td2);
            td.innerText = td2.innerText;
        }
        });
    </script>
{% endblock %}

templates/authorize_chef.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
           Kokkeforespørsler
{% endblock %}

{% block content %}
    {% if chefs %}
        {% for chef in chefs %}
                <!--Et form for hver kokk som venter på godkjenning-->
                <form method="post">
                {% csrf_token %}
                        <div class="page-header">
                        <h3>{{ chef }}, {{ chef.workplace }}</h3>
                            <p>{{ chef.info }}</p>
                        </div>
                    <input type="hidden" name="chef.id" value="{{ chef.id }}">
                <button type="submit" name="permission" class="btn btn-success">Godkjenn</button>
                </form>
        {% endfor %}
    {% else %}
        <p class="text-xl-center">Du har ingen kokker som venter på godkjenning</p>
    {% endif %}
{% endblock %}

templates/base_template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}  {% endblock title%} | Matega</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        {% load static %}
        <link rel="shortcut icon" href="{% static "media/logo/favicon.png" %}">
        <style>
            #content {
                max-width: 1000px;
                margin-top: 78px;
                margin-left: 300px;
            }
            #sidebar {
                position: fixed;
                width: 250px;
                top: 0;
                left: 0;
                height: 100vh;
                z-index: 1;
                background: #C4D290;
                color: #fff;
                transition: all 0.3s;
                overflow: auto;
            }

            #sidebar .sidebar-header {

                padding: 20px;
                background: #9BB07C;
            }

            #sidebar ul p {
                color: #fff;
                padding: 10px;
            }

            #sidebar ul li a {
                padding: 10px;
                font-size: 1.1em;
                display: block;
            }

            #sidebar {
                min-width: 250px;
                max-width: 250px;
                min-height: 100vh;

            }

            #sidebar.active {
                margin-left: -250px;
            }
            #sidebar-header {
                height: 56px;
                background: #658361;
            }
            #sidebarCollapse {
                z-index: 2;
                position: absolute;
                left:10px;
                color: white;
            }
            #ingredients_list {
                padding: 10px 10px 0 20px;
            }
            {% block css %}
            {% endblock %}
        </style>
    </head>
    <body>
        {% include 'navbar.html' %}

        <nav id="sidebar" class="active">
            <div id="sidebar-header">

            </div>
           <div class="sidebar-header">
                <h4>Dine ingredienser</h4>
            </div>
            <ul class="list-unstyled components" id="ingredients_list">
            </ul>
        </nav>

        <div id="content">
             <!--Melding for de som venter på å bli kokk -->
            {% if user.asked_for_perm %}
                <div class="alert alert-info" role="alert">
                    Du venter på kokkegodkjennelse fra admin. Kokkefunksjoner vil derfor være utilgjengelig.
                </div>
            {% endif %}

            <!--Vise alle meldinger under navbaren. Meldinger kan legges til i view med messages.add_message(request, messages.INFO/WARNING/DANGER etc, "melding") -->
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}

            {% endblock content %}
        </div>
        <div>
            {% block registration %}
            {% endblock %}
        </div>
    <!--jQuery og Bootstrap Javascript cdn-->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
            update_owned_ingredients();

        });
        //henter ingredienser fra lokalstorage og viser de i sidebaren
        function update_owned_ingredients() {
            let x = $('#ingredients_list');
            x.html("");

            let arr = JSON.parse(localStorage.getItem('checked')) || [];
            arr.forEach(function (i) {
                $('<li/>')
                    .appendTo('#ingredients_list')
                    .html(i);
                $("[class='"+ i + "']").css('color', 'green');
            });
            if(x.html() === "") {
                x.html("<a href='{% url 'ingredient_search' %}'>Legg til ingredienser</a> for å finne oppskrifter du kan lage")
            }
        }
    </script>
    {% block script %}

    {% endblock %}
    </body>
</html>

templates/chef_edit.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
    Endre brukerinfo
{% endblock %}

{% block content %}
     <div class="container">
     <div class="page-header">
          <h1 align="left"> Endre brukerinfo</h1>
      </div>
        <div class="row">
            <!--Form for endring av kokkeinformasjon-->
            <form method="post" enctype="multipart/form-data" class="col-lg-12">
                {% csrf_token %}
                {% with WIDGET_ERROR_CLASS="is-invalid" %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <!-- Workplace -->
                                <div class="input-group mt-2 mb-3 w-50">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="fa fa-briefcase fa-fw"></span> </div>
                                </div>
                                    {% render_field chef_form.workplace class="form-control" placeholder='Arbeidssted'%}
                                </div>
                                <small class="text-danger">{{ chef_form.workplace.errors }}</small>

                                <!-- Info -->
                                <div class="input-group mt-2 mb-3 w-50">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="fa fa-info-circle fa-fw"></span> </div>
                                </div>
                                    {% render_field chef_form.info class="form-control" placeholder='Ytterligere informasjon'%}
                                </div>
                                <small class="text-danger">{{ chef_form.info.errors }}</small>

                                <!-- Education -->
                                <div class="input-group mt-2 mb-3 w-50">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="fa fa-graduation-cap fa-fw"></span> </div>
                                </div>
                                    {% render_field chef_form.education class="form-control" placeholder='Utdanning'%}
                                </div>
                                <small class="text-danger">{{ chef_form.education.errors }}</small>

                                <!-- Merit -->
                                <div class="input-group mt-2 mb-3 w-50">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="fa fa-star fa-fw"></span> </div>
                                </div>
                                    {% render_field chef_form.merit class="form-control" placeholder='Merit'%}
                                </div>
                                <small class="text-danger">{{ chef_form.merit.errors }}</small>

                                <!-- Image -->
                                {% render_field chef_form.image %}
                                 <small class="text-danger">{{ chef_form.image.errors }}</small>
                                <br>

                                <button type="submit" class="btn btn-success float-right" name="chef_form">Oppdater!</button>
                                <style type="text/css">
                                    .container.custom-container {
                                    padding: 0 100px;
                                    }
                                </style>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            </form>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $("#image-clear_id").css("display","none");
        $("label[for='image-clear_id']").css("display","none");
    </script>
{% endblock %}

templates/chef_site.html
{% extends "base_template.html" %}

{% block title %}
    {{ chef }}
{% endblock %}

{% block content %}
<body>
    <body>
  <div class="container">
        <!-- Overskirfte -->
      <div class="page-header">
          <h1 align="left"> {{ chef }}</h1>
          </br>
      </div>

  <div class = row> <!-- En row rundt hele siden -->
      <!-- Kolonnen til venstre -->
      <div class="col-lg-5">
          <div>
            <img src="{{ chef.image.url }}" height="300px" width="300px" border="50">
          </div>
          <div>
              <ul class="list-unstyled">
                <li><u>Arbeidssted</u>: {{ chef.workplace }}</li>
                <li><u>Utdanning</u>: {{ chef.education }}</li>
                <li><u>Meritt</u>: {{ chef.merit }}</li>
              </ul>
              <div class="custom-container">{{ chef.info|linebreaksbr }}</div>
          </div>
      </div>

      <!-- Kolonnen til høyre -->
      <div class="col-lg-7">
          <div class = "row">
              <h3>{{ chef }} sine oppskrifter</h3>
          </div>
          <div class="row">
            <ul class="list-group w-100">
                {% for rec in recipes %}
                    <a href="{% url 'recipe' rec.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="media">
                            <img class="img-thumbnail" src="{{ rec.image.url }}" style="width: 100px; height: 100px">
                            <div style="padding-left: 10px">
                                <h5 class="mb-1" style="text-align: left">{{ rec.name }}</h5>
                                <small> {{ rec.pub_date }} </small>
                                <p class="mb-1">
                                    <!-- Skriver ut hver ingrediens i oppskriften -->
                                    {% for ing in rec.ingredients.all %}
                                        <span id="{{ ing }}" style="color:red;" class="{{ ing }}">{{ ing }}</span>
                                    {% endfor %}
                                </p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </ul>
          </div>
      </div>
    </div>


  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
       <script>
        let arr = JSON.parse(localStorage.getItem('checked')) || [];
        arr.forEach(function (i) {
            $("[class='"+ i + "']").css('color', 'green');
        });

    </script>
    </body>
</body>
{% endblock %}

templates/comma.html
<!--Kode for komma i lister laget av for-loops-->
{% if not forloop.last %}<span style="color:black">, </span>{% else %}{% endif %}